export const GROUPS = {
  structure: { fr: "Structure", en: "Structure" },
  interne: { fr: "Équipage mobile", en: "Moving assembly" },
  distribution: { fr: "Distribution", en: "Timing" },
  allumage: { fr: "Allumage", en: "Ignition" },
  injection: { fr: "Admission & injection", en: "Intake & injection" },
  echappement: { fr: "Échappement", en: "Exhaust" },
  lubrification: { fr: "Lubrification", en: "Lubrication" },
  refroidissement: { fr: "Refroidissement", en: "Cooling" },
  accessoires: { fr: "Accessoires", en: "Accessories" },
  capteurs: { fr: "Capteurs", en: "Sensors" },
};

export const UI = {
  fr: {
    hint: "Cliquez une pièce · glissez pour tourner",
    explode: "Éclaté",
    explodeBtn: "Éclater",
    assembleBtn: "Remonter",
    filter: "Rechercher une pièce…",
    emptyTitle: "Moteur 4 cylindres en ligne",
    emptyAka: "Schéma pédagogique · essence",
    empty:
      "Ce n’est pas le moteur d’un modèle précis (ni une Clio, ni une 208). C’est un 4 cylindres en ligne essence, 8 soupapes, injection indirecte, pour situer les pièces. Le turbo n’existe que sur les versions suralimentées. L’éclaté montre l’intérieur : pistons, bielles, vilebrequin, soupapes.",
    role: "À quoi ça sert",
    where: "Où ça se trouve",
    symptom: "Signes fréquents",
    note: "Les symptômes aident à comprendre, ce n’est pas un diagnostic. L’intervalle exact est celui du constructeur.",
    subtitle: "Schéma · 40 organes",
  },
  en: {
    hint: "Click a part · drag to rotate",
    explode: "Exploded",
    explodeBtn: "Explode",
    assembleBtn: "Assemble",
    filter: "Search a part…",
    emptyTitle: "Inline-four engine",
    emptyAka: "Teaching diagram · petrol",
    empty:
      "Not a specific car engine. An inline-four petrol, 8 valves, port injection, to show where parts sit. The turbo is only on boosted versions. Exploded view shows the inside: pistons, rods, crank, valves.",
    role: "What it does",
    where: "Where it sits",
    symptom: "Common signs",
    note: "Symptoms help you understand; they are not a diagnosis. Service intervals are the manufacturer’s.",
    subtitle: "Diagram · 40 parts",
  },
};

export const PARTS = [
  {
    id: "bloc-cylindres",
    group: "structure",
    explode: [0, 0, 0],
    fr: {
      name: "Bloc-cylindres",
      aka: "Bloc moteur",
      role: "C’est le corps du moteur. Quatre alésages : les pistons y montent et descendent. Canaux d’eau et d’huile traversent la fonte ou l’alu.",
      where: "Pièce centrale. Tout le reste se boulonne dessus ou dedans.",
      symptom: "Fissure ou joint de chemise : lait au bocal, perte d’eau, surchauffe. Rare, mais grave.",
    },
    en: {
      name: "Engine block",
      aka: "Cylinder block",
      role: "The engine’s body. Four bores for the pistons, plus coolant and oil galleries through the iron or aluminium.",
      where: "The core. Everything else bolts onto or into it.",
      symptom: "A crack or liner leak: milky coolant, water loss, overheating. Rare, and serious.",
    },
  },
  {
    id: "culasse",
    group: "structure",
    explode: [0, 1.25, 0],
    fr: {
      name: "Culasse",
      aka: "Culasse",
      role: "Ferme le haut des cylindres. Elle porte les chambres de combustion, les soupapes et, sur ce schéma, l’arbre à cames (simple arbre en tête).",
      where: "Boulonnée sur le dessus du bloc, séparée par le joint de culasse.",
      symptom: "Joint HS ou culasse voilée après surchauffe : fumée blanche, émulsion (aspect mayonnaise) dans l’huile ou le vase, ralenti instable. D’autres causes existent (échangeur huile/eau, etc.).",
    },
    en: {
      name: "Cylinder head",
      aka: "Head",
      role: "Closes the top of the cylinders. Holds the combustion chambers, valves, and often the camshaft.",
      where: "Bolted on top of the block, with the head gasket in between.",
      symptom: "Blown gasket or a warped head after overheating: white smoke, mayonnaise in the oil, rough idle.",
    },
  },
  {
    id: "joint-culasse",
    group: "structure",
    explode: [0, 0.55, 1.05],
    fr: {
      name: "Joint de culasse",
      aka: "Joint de culasse",
      role: "Assure l’étanchéité (combustion, liquide de refroidissement, huile) entre le bloc et la culasse. Souvent en acier multicouche sur les moteurs récents.",
      where: "Sandwich plat entre le bloc et la culasse.",
      symptom: "Surchauffe, gaz dans le vase d’expansion, perte de puissance. À ne pas « laisser courir ».",
    },
    en: {
      name: "Head gasket",
      aka: "Head gasket",
      role: "Seals combustion, coolant and oil between block and head. Thin, and unforgiving.",
      where: "Flat sandwich between the block and the head.",
      symptom: "Overheating, exhaust in the expansion tank, power loss. Do not drive on it.",
    },
  },
  {
    id: "couvre-culasse",
    group: "structure",
    explode: [0, 1.95, 0],
    fr: {
      name: "Couvre-culasse",
      aka: "Cache-culbuteurs",
      role: "Couvercle supérieur. Garde l’huile de rampe de soupapes à l’intérieur.",
      where: "Sur le dessus de la culasse, souvent en alu ou plastique.",
      symptom: "Fuite d’huile sur la culasse et le collecteur. Joint de cache à remplacer, pas le cache entier.",
    },
    en: {
      name: "Valve cover",
      aka: "Rocker cover",
      role: "Top lid. Keeps cam and valve-train oil inside.",
      where: "On top of the head, aluminium or plastic.",
      symptom: "Oil seeping onto the head and manifold. Replace the gasket, not the whole cover.",
    },
  },
  {
    id: "carter-distribution",
    group: "structure",
    explode: [1.85, 0.15, 0],
    fr: {
      name: "Carter de distribution",
      aka: "Cache courroie",
      role: "Protège courroie et poulies des gravillons et de l’huile. Sans lui, la courroie meurt vite.",
      where: "En bout du moteur, côté opposé au volant (côté courroie).",
      symptom: "Cache fendu ou mal recoupé après un travail : courroie à nu, durée de vie réduite.",
    },
    en: {
      name: "Timing cover",
      aka: "Belt cover",
      role: "Shields the timing belt and pulleys from stones and oil.",
      where: "Engine end opposite the flywheel (belt side).",
      symptom: "A cracked or missing cover leaves the belt exposed and shortens its life.",
    },
  },
  {
    id: "carter-huile",
    group: "lubrification",
    explode: [0, -1.45, 0],
    fr: {
      name: "Carter d’huile",
      aka: "Sump",
      role: "Réservoir d’huile sous le moteur. La pompe y puise, l’huile y retombe.",
      where: "Sous le bloc, boulonné, avec le bouchon de vidange.",
      symptom: "Tache au sol, niveau qui baisse. Un choc sur un dos d’âne peut le fendre.",
    },
    en: {
      name: "Oil pan",
      aka: "Sump",
      role: "Oil reservoir under the engine. The pump draws from it; oil drains back into it.",
      where: "Under the block, with the drain plug.",
      symptom: "Puddle on the floor, falling level. A speed bump hit can split it.",
    },
  },
  {
    id: "pistons",
    group: "interne",
    explode: [0, 0.85, 0.55],
    fr: {
      name: "Pistons",
      aka: "4 pistons",
      role: "Reçoivent la combustion et poussent les bielles. Segments étanches gaz et huile.",
      where: "Dans les alésages du bloc, un par cylindre.",
      symptom: "Casse de segment : fumée bleue, conso d’huile, compression basse.",
    },
    en: {
      name: "Pistons",
      aka: "Four pistons",
      role: "Take the combustion hit and push the rods. Rings seal gas and oil.",
      where: "Inside the block bores, one per cylinder.",
      symptom: "Worn rings: blue smoke, oil use, low compression.",
    },
  },
  {
    id: "bielles",
    group: "interne",
    explode: [0, -0.55, 0.7],
    fr: {
      name: "Bielles",
      aka: "4 bielles",
      role: "Relient chaque piston au vilebrequin. Transforment le va-et-vient en rotation.",
      where: "Entre le pied de piston (axe) et un maneton du vilebrequin.",
      symptom: "Coussinet de bielle endommagé : claquement sourd qui s’amplifie, pression d’huile basse. Il faut s’arrêter, ce n’est pas un bruit à « surveiller ».",
    },
    en: {
      name: "Connecting rods",
      aka: "Four rods",
      role: "Join each piston to the crank. Turn up-and-down into rotation.",
      where: "Between the piston pin and a crank journal.",
      symptom: "A spun bearing: a deep knock that grows, low oil pressure. Stop at once.",
    },
  },
  {
    id: "vilebrequin",
    group: "interne",
    explode: [0, -1.05, 0],
    fr: {
      name: "Vilebrequin",
      aka: "Crankshaft",
      role: "Arbre coudé. Sortie de couple du moteur, vers l’embrayage et la boîte.",
      where: "Dans le bas moteur, palierné dans le bloc, débouchant sur le volant.",
      symptom: "Jeu aux paliers : bruit de fond, pression d’huile. Réfection moteur.",
    },
    en: {
      name: "Crankshaft",
      aka: "Crank",
      role: "The bent shaft. Engine torque leaves here, toward clutch and gearbox.",
      where: "Bottom end, in block bearings, ending at the flywheel.",
      symptom: "Worn mains: a rumble, low oil pressure. Engine rebuild territory.",
    },
  },
  {
    id: "volant-moteur",
    group: "interne",
    explode: [-1.75, -0.15, 0],
    fr: {
      name: "Volant moteur",
      aka: "Volant d’inertie",
      role: "Masse qui lisse les à-coups des 4 temps. Couronne dentée pour le démarreur. Sur une boîte manuelle, une face reçoit l’embrayage. Sur une automatique, on trouve plutôt un plateau (flexplate).",
      where: "Bout du vilebrequin, côté boîte de vitesses.",
      symptom: "Vibrations à l’embrayage (volant bimasse fatigué), ou denture râpée : démarreur qui crisse.",
    },
    en: {
      name: "Flywheel",
      aka: "Flexplate on autos",
      role: "Mass that smooths the four-stroke pulses. Ring gear for the starter. Clutch face.",
      where: "Crank end, gearbox side.",
      symptom: "Clutch judder (tired dual-mass), or a chewed ring gear: starter scream.",
    },
  },
  {
    id: "poulie-vilebrequin",
    group: "distribution",
    explode: [1.55, -0.35, 0],
    fr: {
      name: "Poulie damper",
      aka: "Poulie de vilebrequin",
      role: "Entraîne la courroie d’accessoires. Le damper absorbe les torsions du vilebrequin.",
      where: "Bout du vilebrequin, côté distribution, devant la poulie de courroie de distro.",
      symptom: "Caoutchouc du damper décollé : vibrations, courroie d’accessoires qui saute.",
    },
    en: {
      name: "Crank pulley",
      aka: "Harmonic damper",
      role: "Drives the accessory belt. The damper soaks up crank twist.",
      where: "Crank snout, timing side, in front of the timing sprocket.",
      symptom: "Separated rubber: vibration, accessory belt that walks off.",
    },
  },
  {
    id: "arbre-cames",
    group: "distribution",
    explode: [0, 1.5, -0.35],
    fr: {
      name: "Arbre à cames",
      aka: "AAC",
      role: "Cames qui ouvrent les soupapes au bon moment. Entraîné par la courroie de distribution.",
      where: "Dans la culasse (ici : simple arbre en tête).",
      symptom: "Calage faux après courroie : ratés, pas de démarrage, parfois soupapes tordues.",
    },
    en: {
      name: "Camshaft",
      aka: "Cam",
      role: "Lobes that open the valves on time. Driven by the timing belt.",
      where: "In the head (this model: single overhead cam).",
      symptom: "Wrong timing after a belt job: misfires, no start, sometimes bent valves.",
    },
  },
  {
    id: "soupapes",
    group: "distribution",
    explode: [0, 1.55, 0.4],
    fr: {
      name: "Soupapes",
      aka: "Admission + échappement",
      role: "Admission : laissent entrer l’air. Échappement : laissent sortir les gaz. 2 par cylindre ici.",
      where: "Têtes dans la chambre, tiges vers l’arbre à cames.",
      symptom: "Soupape brûlée : cylindre qui lâche, compression fuyant à l’échappement.",
    },
    en: {
      name: "Valves",
      aka: "Intake + exhaust",
      role: "Intake valves let air in. Exhaust valves let gas out. Two per cylinder here.",
      where: "Heads in the chamber, stems toward the cam.",
      symptom: "A burnt valve: one cylinder gone, compression leaking out the exhaust.",
    },
  },
  {
    id: "ressorts-soupapes",
    group: "distribution",
    explode: [0, 1.75, 0.15],
    fr: {
      name: "Ressorts de soupapes",
      aka: "8 ressorts",
      role: "Referment les soupapes après la came. Sans eux, la soupape reste ouverte.",
      where: "Autour de chaque tige, sous le couvre-culasse.",
      symptom: "Ressort cassé : claquement, un cylindre mort, parfois soupape qui tombe dans le cylindre.",
    },
    en: {
      name: "Valve springs",
      aka: "Eight springs",
      role: "Close the valves after the cam lobe. Without them the valve stays open.",
      where: "Around each stem, under the valve cover.",
      symptom: "Broken spring: a tick, a dead cylinder, sometimes a valve dropped into the bore.",
    },
  },
  {
    id: "courroie-distribution",
    group: "distribution",
    explode: [1.45, 0.35, 0],
    fr: {
      name: "Courroie de distribution",
      aka: "Courroie de distro",
      role: "Synchronise vilebrequin et arbre à cames. Si elle casse sur un moteur interférent : pistons contre soupapes.",
      where: "Sous le carter, en bout de moteur, sur les poulies crantées.",
      symptom: "Moteur qui coupe net, plus de compression. Intervalle constructeur à respecter, pas l’âge seul.",
    },
    en: {
      name: "Timing belt",
      aka: "Cam belt",
      role: "Keeps crank and cam in time. On an interference engine a snap means pistons vs valves.",
      where: "Under the cover, on the toothed pulleys at the engine end.",
      symptom: "Engine stops dead, no compression. Follow the service interval, not just age.",
    },
  },
  {
    id: "poulies-distribution",
    group: "distribution",
    explode: [1.25, 0.25, 0],
    fr: {
      name: "Poulies de distribution",
      aka: "Pignons crantés",
      role: "Pignon vilebrequin + pignon arbre à cames. Les crans calent le moteur au degré près.",
      where: "Bouts d’arbres, sous la courroie.",
      symptom: "Clavette ou poulie desserrée : calage qui dérive, cliquetis, voyant moteur.",
    },
    en: {
      name: "Timing pulleys",
      aka: "Sprockets",
      role: "Crank sprocket + cam sprocket. The teeth set timing to the degree.",
      where: "On the shaft ends, under the belt.",
      symptom: "A loose pulley or key: timing drift, rattle, check-engine light.",
    },
  },
  {
    id: "galet-tendeur",
    group: "distribution",
    explode: [1.55, -0.05, 0.45],
    fr: {
      name: "Galet tendeur",
      aka: "Tendeur de courroie",
      role: "Garde la courroie de distribution tendue. Se change avec la courroie, pas après.",
      where: "Sur le bloc, dans le triangle de la courroie.",
      symptom: "Roulement grippé : sifflement puis casse de courroie. Toujours en kit avec la courroie.",
    },
    en: {
      name: "Timing tensioner",
      aka: "Belt tensioner",
      role: "Keeps the timing belt taut. Replace it with the belt, not later.",
      where: "On the block, inside the belt run.",
      symptom: "A seized bearing: a squeal, then a snapped belt. Always a kit, not the belt alone.",
    },
  },
  {
    id: "pompe-huile",
    group: "lubrification",
    explode: [0.45, -1.55, 0.45],
    fr: {
      name: "Pompe à huile",
      aka: "Pompe de lubrification",
      role: "Aspire l’huile du carter et alimente les paliers, l’équipage mobile et, s’il y en a un, le turbo. Sans pression d’huile, le moteur se détruit en très peu de temps.",
      where: "Bas moteur, souvent entraînée par le vilebrequin.",
      symptom: "Manomètre à zéro, voyant rouge : on coupe, on ne « rentre pas à la maison ».",
    },
    en: {
      name: "Oil pump",
      aka: "Lube pump",
      role: "Draws oil from the pan and feeds bearings, cam, turbo. No pressure, the engine dies in seconds.",
      where: "Bottom end, often crank-driven.",
      symptom: "Gauge at zero, red oil light: switch off. Do not drive it home.",
    },
  },
  {
    id: "filtre-huile",
    group: "lubrification",
    explode: [0.35, -0.55, 1.15],
    fr: {
      name: "Filtre à huile",
      aka: "Cartouche / spin-on",
      role: "Retient limaille et suie. À chaque vidange, un filtre neuf. Pas de débat.",
      where: "Vissé sur le bloc, accessible par le dessous ou le côté.",
      symptom: "Filtre oublié ou mal serré : fuite massive au premier démarrage après vidange.",
    },
    en: {
      name: "Oil filter",
      aka: "Canister / spin-on",
      role: "Catches grit and soot. New filter with every oil change. No debate.",
      where: "Screwed on the block, from below or the side.",
      symptom: "Forgotten or loose after a service: a flood of oil on first start.",
    },
  },
  {
    id: "jauge-huile",
    group: "lubrification",
    explode: [0.95, 0.85, 0.85],
    fr: {
      name: "Jauge d’huile",
      aka: "Jauge à huile",
      role: "Permet de lire le niveau, moteur froid, voiture à plat, entre les repères min et max.",
      where: "Tube collé au bloc, poignée souvent jaune ou orange.",
      symptom: "Niveau sous min : claquement, casse. Au-dessus de max : fumée bleue, catalyseur en danger.",
    },
    en: {
      name: "Dipstick",
      aka: "Oil stick",
      role: "Reads level cold, on level ground. Between min and max. Not decoration.",
      where: "Tube on the block, often a yellow or orange handle.",
      symptom: "Below min: knock, then failure. Above max: blue smoke, catalyst at risk.",
    },
  },
  {
    id: "bougies",
    group: "allumage",
    explode: [0, 2.15, 0.05],
    fr: {
      name: "Bougies d’allumage",
      aka: "4 bougies",
      role: "Étincelle qui enflamme le mélange. Sans elles le moteur tourne au démarreur mais ne part pas.",
      where: "Vissées dans la culasse, une par cylindre, sous les bobines ici.",
      symptom: "Ratés à froid, ralenti irrégulier, voyant moteur. L’intervalle dépend du type de bougie (cuivre, platine, iridium) et du carnet constructeur — il n’y a pas un kilométrage unique.",
    },
    en: {
      name: "Spark plugs",
      aka: "Four plugs",
      role: "The spark that lights the mixture. Without them the engine cranks but never fires.",
      where: "Screwed into the head, one per cylinder, under the coils here.",
      symptom: "Cold misfires, fuel use, check-engine light. 60–100k km depending on iridium vs copper.",
    },
  },
  {
    id: "bobines",
    group: "allumage",
    explode: [0, 2.4, 0],
    fr: {
      name: "Bobines d’allumage",
      aka: "Bobines crayons (COP)",
      role: "Transforment 12 V en dizaines de milliers de volts pour la bougie. Ici : une bobine par cylindre.",
      where: "Enfoncées sur chaque bougie, sur le dessus de la culasse.",
      symptom: "Raté sur un cylindre, parfois à l’humidité. On permute pour confirmer, on ne change pas les 4 au hasard.",
    },
    en: {
      name: "Ignition coils",
      aka: "Coil-on-plug",
      role: "Step 12 V up to tens of thousands for the plug. One coil per cylinder here.",
      where: "Sat on each plug, on top of the head.",
      symptom: "A single-cylinder misfire, often in the wet. Swap to confirm; don’t replace all four on a guess.",
    },
  },
  {
    id: "injecteurs",
    group: "injection",
    explode: [0, 0.85, 1.2],
    fr: {
      name: "Injecteurs",
      aka: "4 injecteurs",
      role: "Pulvérisent l’essence. Sur ce schéma : injection indirecte (dans l’admission). Beaucoup de moteurs récents injectent directement dans le cylindre.",
      where: "Sous la rampe, visés vers les conduits d’admission.",
      symptom: "Ralenti instable, fumée, un cylindre plus froid. Encrassement ou fuite au joint.",
    },
    en: {
      name: "Injectors",
      aka: "Four injectors",
      role: "Spray fuel into the intake (port injection here). Dose and timing come from the ECU.",
      where: "Under the rail, aimed into the intake ports.",
      symptom: "Unsteady idle, smoke, one cold cylinder. Coking or a leaking O-ring.",
    },
  },
  {
    id: "rampe-injection",
    group: "injection",
    explode: [0, 1.15, 1.35],
    fr: {
      name: "Rampe d’injection",
      aka: "Rail",
      role: "Tube commun qui alimente les quatre injecteurs à la même pression.",
      where: "Le long de l’admission, au-dessus des injecteurs.",
      symptom: "Fuite d’essence : odeur à chaud, ralenti qui monte. Pas de bricolage avec un collier.",
    },
    en: {
      name: "Fuel rail",
      aka: "Injector rail",
      role: "Common pipe that feeds all four injectors at the same pressure.",
      where: "Along the intake, above the injectors.",
      symptom: "A fuel smell when hot, idle that climbs. Not a hose-clamp job.",
    },
  },
  {
    id: "collecteur-admission",
    group: "injection",
    explode: [0, 0.85, 1.55],
    fr: {
      name: "Collecteur d’admission",
      aka: "Pipe d’admission",
      role: "Répartit l’air du papillon vers les 4 cylindres. Le volume compte pour le couple à bas régime.",
      where: "Flasqué sur la culasse, côté opposé à l’échappement.",
      symptom: "Joint fuyard : sifflement, ralenti fou, codes mélange pauvre.",
    },
    en: {
      name: "Intake manifold",
      aka: "Inlet manifold",
      role: "Splits throttle-body air to the four cylinders. Volume helps low-end torque.",
      where: "Bolted to the head, opposite the exhaust.",
      symptom: "A leaking gasket: a whistle, hunting idle, lean codes.",
    },
  },
  {
    id: "boitier-papillon",
    group: "injection",
    explode: [0, 0.9, 2.05],
    fr: {
      name: "Boîtier papillon",
      aka: "Throttle body",
      role: "Volet qui dose l’air. Ici électronique : le pied sur l’accélérateur parle au calculateur, pas à un câble.",
      where: "Entrée du collecteur d’admission.",
      symptom: "Papillon encrassé : ralenti bas, à-coups à la réaccélération. Nettoyage, pas toujours un boîtier neuf.",
    },
    en: {
      name: "Throttle body",
      aka: "Throttle",
      role: "Flap that meters air. Electronic here: the pedal talks to the ECU, not a cable.",
      where: "On the intake manifold mouth.",
      symptom: "A coked flap: low idle, a stumble off idle. Clean it before you buy a new body.",
    },
  },
  {
    id: "collecteur-echappement",
    group: "echappement",
    explode: [0, 0.45, -1.55],
    fr: {
      name: "Collecteur d’échappement",
      aka: "Pipe d’échappement",
      role: "Ramène les gaz brûlés des 4 cylindres vers la ligne. Très chaud, dilate, fuit aux joints.",
      where: "Flasqué sur la culasse, côté opposé à l’admission.",
      symptom: "Claquement métallique à froid, odeur de gaz dans l’habitacle, son rauque.",
    },
    en: {
      name: "Exhaust manifold",
      aka: "Header",
      role: "Gathers burnt gas from four cylinders into the downpipe. Hot, it grows, and gaskets leak.",
      where: "Bolted to the head, opposite the intake.",
      symptom: "A metallic tick from cold, exhaust smell in the cabin, a raspy note.",
    },
  },
  {
    id: "sonde-lambda",
    group: "echappement",
    explode: [0.25, 0.05, -1.85],
    fr: {
      name: "Sonde lambda",
      aka: "Sonde à oxygène",
      role: "Mesure l’oxygène restant dans les gaz. Le calculateur s’en sert pour corriger la richesse. Il y a souvent une sonde avant catalyseur, parfois une seconde après.",
      where: "Dans le collecteur, la descente, ou juste avant le catalyseur — selon le moteur.",
      symptom: "Conso en hausse, voyant moteur, ralenti pauvre. Une sonde lente se change, on ne la « recale » pas.",
    },
    en: {
      name: "Lambda sensor",
      aka: "O2 sensor",
      role: "Reads oxygen in the exhaust. The ECU trims fuel from that.",
      where: "Screwed into the manifold or just after, before the catalyst.",
      symptom: "Higher fuel use, check-engine light, a lean idle. A lazy sensor is replaced, not recoded.",
    },
  },
  {
    id: "turbo",
    group: "echappement",
    explode: [0.7, 0.15, -2.05],
    fr: {
      name: "Turbocompresseur",
      aka: "Turbo",
      role: "Uniquement sur les versions suralimentées. Les gaz font tourner une turbine, qui comprime l’air d’admission : plus d’air, plus de couple.",
      where: "En sortie de collecteur d’échappement, avec une alimentation d’huile et souvent de liquide de refroidissement.",
      symptom: "Manque de souffle, sifflement inhabituel, fumée bleue. Axe en jeu ou huile cokéfiée. Un ralenti de quelques secondes après un trajet chargé reste une précaution, pas une règle universelle.",
    },
    en: {
      name: "Turbocharger",
      aka: "Turbo",
      role: "Exhaust spins a turbine that packs intake air. More air, more torque. Common on recent fours.",
      where: "On the exhaust manifold outlet, with an oil feed and often coolant.",
      symptom: "A whistle, blue smoke, no boost. Coked oil or shaft play. Idle 30 s before shutdown when hot.",
    },
  },
  {
    id: "pompe-eau",
    group: "refroidissement",
    explode: [1.2, 0.05, 0.75],
    fr: {
      name: "Pompe à eau",
      aka: "Pompe de LDR",
      role: "Fait circuler le liquide de refroidissement dans le bloc, la culasse et le radiateur. Selon les moteurs, elle est entraînée par la courroie de distribution, la courroie d’accessoires, ou elle est électrique.",
      where: "Côté distribution, sur le bloc.",
      symptom: "Surchauffe, fuite par le trou de « weep », bruit de roulement. Pas de rustine.",
    },
    en: {
      name: "Water pump",
      aka: "Coolant pump",
      role: "Moves coolant through block, head, radiator. Often timing-belt driven: replace it in the same kit.",
      where: "Timing side, on the block.",
      symptom: "Overheating, drip from the weep hole, a bearing growl. No patch.",
    },
  },
  {
    id: "thermostat",
    group: "refroidissement",
    explode: [0.75, 0.7, 1.0],
    fr: {
      name: "Thermostat",
      aka: "Calorstat",
      role: "Reste fermé à froid pour que le moteur monte en température, puis s’ouvre vers le radiateur. La température de régime se situe souvent autour de 90 °C, pas sur tous les moteurs.",
      where: "Boîtier en sortie de culasse, avant la durite haute.",
      symptom: "Bloqué fermé : aiguille dans le rouge. Bloqué ouvert : jamais de chauffage, conso, thermostat à changer.",
    },
    en: {
      name: "Thermostat",
      aka: "Coolant thermostat",
      role: "Stays shut from cold so the engine warms fast, then opens to the radiator. Running temp around 90 °C.",
      where: "Housing on the head outlet, before the top hose.",
      symptom: "Stuck shut: needle in the red. Stuck open: no cabin heat, extra fuel. Replace it.",
    },
  },
  {
    id: "durite-refroidissement",
    group: "refroidissement",
    explode: [0.55, 1.05, 1.15],
    fr: {
      name: "Durite de LDR",
      aka: "Durite haute",
      role: "Flexible qui mène le liquide chaud vers le radiateur. Le caoutchouc vieillit, pore et pète.",
      where: "Entre le boîtier thermostat et le haut du radiateur (ici : amorce côté moteur).",
      symptom: "Durite boursouflée ou fendue, niveau qui baisse sans fuite visible au carter. À remplacer par paire, colliers neufs.",
    },
    en: {
      name: "Coolant hose",
      aka: "Top hose",
      role: "Carries hot coolant toward the radiator. Rubber ages, weeps, then bursts.",
      where: "Thermostat housing to the radiator top (here: the engine-side stub).",
      symptom: "A swollen or split hose, level dropping with no sump leak. Replace as a pair, new clamps.",
    },
  },
  {
    id: "demarreur",
    group: "accessoires",
    explode: [-1.85, -0.55, 0.7],
    fr: {
      name: "Démarreur",
      aka: "Motorin",
      role: "Moteur électrique : son pignon attaque la couronne du volant pour lancer le vilebrequin.",
      where: "Flasqué cloche d’embrayage / bas moteur, côté volant.",
      symptom: "Clic-clic : souvent batterie ou contacteur. Grognement sans lancer : démarreur ou masselottes. Ce n’est pas toujours « le démarreur ».",
    },
    en: {
      name: "Starter motor",
      aka: "Starter",
      role: "Electric motor: its pinion hits the flywheel ring gear and cranks the engine.",
      where: "On the bellhousing / block, flywheel side.",
      symptom: "Click-click: often battery or solenoid. A grind with no spin: starter or bendix. It is not always “the starter”.",
    },
  },
  {
    id: "alternateur",
    group: "accessoires",
    explode: [1.35, 0.75, 0.95],
    fr: {
      name: "Alternateur",
      aka: "Générateur",
      role: "Recharge la batterie dès que le moteur tourne, alimente l’électrique. Entraîné par la courroie d’accessoires.",
      where: "Haut côté distribution, poulie vers la courroie serpentine.",
      symptom: "Batterie qui se vide en roulant, voyant batterie, phares qui baissent au ralenti. Tester avant d’accuser la batterie.",
    },
    en: {
      name: "Alternator",
      aka: "Generator",
      role: "Charges the battery once the engine runs, and feeds the electrics. Driven by the accessory belt.",
      where: "Upper timing side, pulley into the serpentine belt.",
      symptom: "Battery going flat on the move, charge light, headlights dipping at idle. Test it before you blame the battery.",
    },
  },
  {
    id: "courroie-accessoires",
    group: "accessoires",
    explode: [1.7, 0.35, 0.55],
    fr: {
      name: "Courroie d’accessoires",
      aka: "Serpentine / accessoires",
      role: "Entraîne alternateur, pompe à eau parfois, climatisation. Rien à voir avec la courroie de distribution.",
      where: "Devant le moteur, sur les poulies damper / alternateur / galet.",
      symptom: "Cui-cui à froid, traces de glaçage. Une courroie lisse ou fendue se change, le galet souvent avec.",
    },
    en: {
      name: "Accessory belt",
      aka: "Serpentine belt",
      role: "Drives alternator, sometimes the water pump, air-con. Not the timing belt.",
      where: "Front of the engine, over damper / alternator / idler.",
      symptom: "A cold squeal, a glazed face. A cracked belt is replaced, usually with the idler.",
    },
  },
  {
    id: "galet-accessoires",
    group: "accessoires",
    explode: [1.55, 0.55, 0.7],
    fr: {
      name: "Galet d’accessoires",
      aka: "Fou / tendeur serpentine",
      role: "Tient et tend la courroie d’accessoires. Roulement, donc usure.",
      where: "Dans le parcours de la serpentine, sur le support moteur.",
      symptom: "Grondeau qui suit le régime, courroie qui se décale. Se change avec la courroie.",
    },
    en: {
      name: "Accessory idler",
      aka: "Serpentine tensioner",
      role: "Guides and tensions the accessory belt. It is a bearing, so it wears.",
      where: "In the serpentine run, on the engine bracket.",
      symptom: "A growl that tracks rpm, a belt that walks. Replace it with the belt.",
    },
  },
  {
    id: "capteur-pmh",
    group: "capteurs",
    explode: [-1.15, -0.75, -0.55],
    fr: {
      name: "Capteur PMH",
      aka: "Capteur vilebrequin",
      role: "Dit au calculateur où en est le vilebrequin. Sans ce signal : plus d’injection, plus d’étincelle.",
      where: "Visé vers une cible sur le volant ou le vilebrequin, bas moteur.",
      symptom: "Coupe net, redémarre parfois à chaud. Un classique « elle ne veut plus partir ».",
    },
    en: {
      name: "Crank sensor",
      aka: "CKP / TDC sensor",
      role: "Tells the ECU where the crank is. No signal: no fuel, no spark.",
      where: "Aimed at a target on the flywheel or crank, bottom end.",
      symptom: "Dies dead, sometimes restarts hot. A classic no-start.",
    },
  },
  {
    id: "capteur-arbre-cames",
    group: "capteurs",
    explode: [1.15, 1.55, -0.55],
    fr: {
      name: "Capteur d’arbre à cames",
      aka: "CMP",
      role: "Repère le cycle (quel cylindre est en combustion). Sert au calage et à l’injection séquentielle.",
      where: "Sur la culasse, face à l’arbre à cames ou sa poulie.",
      symptom: "Démarrage long, codes de calage, parfois mode dégradé. Moins brutal qu’un PMH HS.",
    },
    en: {
      name: "Cam sensor",
      aka: "CMP",
      role: "Marks the cycle (which cylinder is on fire). Used for timing and sequential injection.",
      where: "On the head, facing the cam or its pulley.",
      symptom: "A long crank, cam/crank codes, sometimes limp mode. Kinder than a dead crank sensor.",
    },
  },
  {
    id: "capteur-temperature",
    group: "capteurs",
    explode: [-0.85, 0.95, 0.85],
    fr: {
      name: "Sonde de température d’eau",
      aka: "ECT",
      role: "Dit si le moteur est froid ou chaud. Le calculateur enrichit à froid là-dessus. L’aiguille du tableau aussi, parfois.",
      where: "Dans un puits de culasse ou le boîtier thermostat, au contact du LDR.",
      symptom: "Ventilo en permanence, conso, ou au contraire surchauffe « invisible » si la sonde ment.",
    },
    en: {
      name: "Coolant temp sensor",
      aka: "ECT",
      role: "Says whether the engine is cold or hot. The ECU richens from that. The dash gauge sometimes too.",
      where: "In a head well or the thermostat housing, in the coolant.",
      symptom: "Fans stuck on, extra fuel — or a “hidden” overheat if the sensor lies.",
    },
  },
  {
    id: "capteur-pression-huile",
    group: "capteurs",
    explode: [-0.55, -0.35, 1.05],
    fr: {
      name: "Capteur de pression d’huile",
      aka: "Manocontact",
      role: "Allume le voyant rouge si la pression tombe. Ce n’est pas une jauge de niveau.",
      where: "Vissé dans le bloc, galerie d’huile.",
      symptom: "Voyant au ralenti à chaud : parfois le capteur, parfois la pompe. On mesure au manomètre avant de tout démonter.",
    },
    en: {
      name: "Oil pressure sensor",
      aka: "Oil switch",
      role: "Turns on the red light if pressure falls. It is not a level gauge.",
      where: "Screwed into the block, in an oil gallery.",
      symptom: "Light at hot idle: sometimes the sensor, sometimes the pump. Measure with a gauge before you strip it.",
    },
  },
];
